apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-cache-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-cache-controller
rules:
- apiGroups:
  - ""
  resources:
    - "pods"
  verbs:
    - "get"
    - "watch"
    - "list"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: image-cache-controller
subjects:
- kind: ServiceAccount
  name: image-cache-controller
roleRef:
  kind: ClusterRole
  name: image-cache-controller
  apiGroup: rbac.authorization.k8s.io
