apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/elotl/kip/deploy/manifests/kip/base?ref=v0.0.9
namespace: ${NAMESPACE}
resources:
- image-cache-controller.yaml
- fluentd.yaml
- cloudwatch.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: provider
  path: patch-provider-statefulset.yaml
- target:
    version: v1
    kind: ServiceAccount
    name: provider
  patch: |-
    - op: add
      path: /metadata/annotations
      value: {eks.amazonaws.com/role-arn: "${KIP_SERVICE_ACCOUNT_ROLE_ARN}"}
images:
- name: elotl/kip
  newName: ${IMAGE_REGISTRY}/kip
  newTag: ${IMAGE_TAG}
- name: elotl/init-cert
  newName: ${IMAGE_REGISTRY}/init-cert
  newTag: ${IMAGE_TAG}
- name: k8s.gcr.io/kube-proxy
  newName: ${IMAGE_REGISTRY}/kube-proxy
  newTag: ${IMAGE_TAG}
- name: elotl/image-cache-controller
  newName: ${IMAGE_REGISTRY}/image-cache-controller
  newTag: ${IMAGE_TAG}
- name: elotl/kip-aws-meteringagent
  newName: ${IMAGE_REGISTRY}/kip-aws-meteringagent
  newTag: ${IMAGE_TAG}
configMapGenerator:
- name: config
  files:
  - provider.yaml
  behavior: merge
