---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uptime
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/status
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: uptime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uptime
subjects:
- kind: ServiceAccount
  name: uptime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime
spec:
  selector:
    matchLabels:
      app: uptime
  replicas: 1
  template:
    metadata:
      labels:
        app: uptime
    spec:
      serviceAccount: uptime
      containers:
      - command:
        - /kip-uptime
        - --logtostderr
        - --v=5
        name: kip-uptime
        image: 689494258501.dkr.ecr.us-east-1.amazonaws.com/elotl/kip-uptime
